# list your R source files that you want to track here:
sources := 
# list all the Sweave reports you want to build here:
reports := report.Rnw
# list here any eventual extra target you want to build
targets := 